name: Artifact Promotion to prod

on:
  # Run this workflow when pushed to main
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
    Synapse-artifact-promotion:
        # You also can use the self-hosted runners.
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - uses: azure/synapse-workspace-deployment@release-1.7.0
          with:
            TargetWorkspaceName: 'cicd-sw-prd'
            #TemplateFile: 'cicd-sw-dev/TemplateForWorkspace.json'
            #ParametersFile: 'cicd-sw-dev/TemplateParametersForWorkspace.json'
            #OverrideArmParameters: 'cicd-sw-dev/OverrideParameters.yaml'
            environment: 'Azure Public'
            resourceGroup: 'cicd-rg-prd'
            clientId: '9ed93616-993c-48ea-986e-f826e95a49a6'
            clientSecret: '4j68Q~e7NVH6PItnUi9-oPRJNS616VPjzz7f5bBo'
            subscriptionId: '790df00a-519e-44c6-91ea-76b13096cdbe'
            tenantId: '8b60cac9-42b5-462d-a1e5-dfb907b73d02'
            DeleteArtifactsNotInTemplate: 'True'
            ArtifactsFolder: 'synapse'
            operation: 'validateDeploy'
            managedIdentity: 'False'
